---
- name: Listen for events from the AAP activity stream
  hosts: all
  sources:
    - name: Listen to default webhook messages on port 5001
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Web Server process down
      condition: event.payload.text == "Apache server is down on client-vm"
      action:
        run_workflow_template:
          name: WFJT-Remediate-Web-Server
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               sleep: 1
