---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  ## Define the conditions we are looking for
  rules:
    - name: Restart Web Server
      condition: event.payload.message == "Apache server is down"
  ## Define the action we should take should the condition be met
      run_job_template:
        name: StartHTTPD
        organization: Default
        job_args:
          extra_vars:
             message: from eda
             sleep: 1
